
[tool.poetry]
name = "datalens-control-api"
version = "0.0.0"
description = ""
authors = ["Dmitry Fedorov <dmifedorov@yandex-team.ru>", "Aleksei Konstantinov konstasa@yandex-team.ru"]
packages = [{include = "dl_control_api"}]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
Flask = ">=2.0.3"
blinker = ">=1.5"
raven = ">=6.10.0"
datalens-version = {path = "../../lib/dl_version"}
datalens-sqlalchemy-postgres = {path = "../../lib/dl_sqlalchemy_postgres"}
datalens-utils = {path = "../../lib/dl_utils"}
datalens-sqlalchemy-common = {path = "../../lib/dl_sqlalchemy_common"}
datalens-sqlalchemy-clickhouse = {path = "../../lib/dl_sqlalchemy_clickhouse"}
datalens-connector-postgresql = {path = "../../lib/dl_connector_postgresql"}
datalens-connector-clickhouse = {path = "../../lib/dl_connector_clickhouse"}
datalens-connector-greenplum = {path = "../../lib/dl_connector_greenplum"}
datalens-core = {path = "../../lib/dl_core"}
datalens-app-tools = {path = "../../lib/dl_app_tools"}
datalens-model-tools = {path = "../../lib/dl_model_tools"}
datalens-api-lib = {path = "../../lib/dl_api_lib"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = []



[datalens_ci]
skip_test = true

[[tool.poetry.source]]
name = "ya"
url = "https://pypi.yandex-team.ru/simple/"
priority = "default"

[tool.mypy]
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true
strict_optional = true
