services:
  db-clickhouse:
    build:
      context: docker-compose
      dockerfile: Dockerfile.db-clickhouse
    depends_on:
    - zookeeper-1
  db-mssql:
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=qweRTY123
    image: some.cr.example/datalens/mssql-server-linux@sha256:6522290393006d93b88f63a295c5137010e4e0fea548d3fce9892c07262f7a1a
  db-mysql:
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=1
    - MYSQL_DATABASE=common_test
    - MYSQL_USER=datalens
    - MYSQL_PASSWORD=qwerty
    image: some.cr.example/datalens/mysql@sha256:d8e4032005f53a774f2361281ebf61fa3d7635d5dacf9c58bc54e823ddcf9f1d
  db-postgres:
    environment:
    - POSTGRES_DB=common_test
    - POSTGRES_USER=datalens
    - POSTGRES_PASSWORD=qwerty
    image: some.cr.example/datalens/postgres@sha256:094358a1a64da927d5c26dcac9dad022cf0db840b6b627b143e5e4fd9adf982b
  db-postgres-fresh:
    environment:
    - POSTGRES_DB=common_test
    - POSTGRES_USER=datalens
    - POSTGRES_PASSWORD=qwerty
    image: some.cr.example/datalens/postgres@sha256:3335d0494b62ae52f0c18a1e4176a83991c9d3727fe67d8b1907b569de2f6175
  init-db:
    build:
      context: docker-compose
      dockerfile: Dockerfile.init-db
    depends_on:
    - db-clickhouse
    - db-postgres
    - db-mysql
    - db-mssql
  pg-us:
    build:
      context: ../../lib/testenv-common/images
      dockerfile: Dockerfile.pg-us
    environment:
      POSTGRES_DB: us-db-ci_purgeable
      POSTGRES_PASSWORD: us
      POSTGRES_USER: us
  redis-caches:
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    image: some.cr.example/datalens/redis@sha256:3127620da977815556439a9dc347fff89432a79b6bb6e93a16f20ac4a34ce337
  s3-storage:
    build:
      context: ../../lib/testenv-common/images
      dockerfile: Dockerfile.s3-storage
    command: bash /data/entrypoint.sh
  us:
    labels:
      datalens.ci.service: united-storage
    build:
      context: ../../lib/testenv-common/images
      dockerfile: Dockerfile.us
    depends_on:
    - pg-us
    environment:
      AUTH_POLICY: required
      MASTER_TOKEN: AC1ofiek8coB
      POSTGRES_DSN_LIST: postgres://us:us@pg-us:5432/us-db-ci_purgeable
  zookeeper-1:
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
      ports: 1,2,3,just for test
    image: some.cr.example/datalens/zookeeper@sha256:ad460bd234a3166cb37e14a1526d677052f7c42e1d1dccd040ca3e24ed1bec1f
version: '3.7'
x-constants:
  DB_MSSQL_CONTAINER_NAME: bi-core_db-mssql
  DB_ORACLE_CONTAINER_NAME: bi-core_db-oracle
  US_MASTER_TOKEN: AC1ofiek8coB
  ports: 1,2,3,just for test
